name: Static Analysis

on:
  pull-request:
  #workflow_call: # workflow_call for future reusable workflow use

  jobs:
    test:
      runs-on: ubuntu-latest
      steps:
      - name: Step 1
        run:  echo "HIIII"

